{
  "id": 1407,
  "name": "ERROR_CLUSTER_MAX_NODES_IN_CLUSTER",
  "description": "A new node can not be added since this cluster is already at its maximum number of nodes.",
  "external_url": "https://github.oblokos.com/?art=ERROR_CLUSTER_MAX_NODES_IN_CLUSTER",
  "image": "https://github.oblokos.com/art/ERROR_CLUSTER_MAX_NODES_IN_CLUSTER.png",
  "opensea_url": "https://opensea.io/assets/matic/0x252f9390feb63aeb00042dd5c4ff84af33f42b85/1407",
  "attributes": [
    {
      "trait_type": "artist",
      "value": "0x5Ae65e30834f61B26A25D9F9F0847c3da11dD391"
    },
    {
      "trait_type": "collection",
      "value": "Metaverse First Contact"
    },
    {
      "trait_type": "error_code",
      "value": "5934 (0x172E)"
    },
    {
      "display_type": "number",
      "trait_type": "frame",
      "value": "20566"
    },
    {
      "display_type": "number",
      "trait_type": "index",
      "value": 0.636
    },
    {
      "display_type": "number",
      "trait_type": "level",
      "value": 0
    }
  ]
}